In [5]:
import numpy as np
a=np.array([[1,2],[23,32]])
np.ndim(a)

2

In [6]:
a[1]

array([23, 32])

In [7]:
b=np.array([1,2,3,4])
b[0]

1

In [8]:
b[2]

3

In [9]:
b[3]


4

In [11]:
a.itemsize

4

In [12]:
b.dtype

dtype('int32')

In [13]:
b=np.array([1,2,3,4],dtype=np.float64)
b.itemsize

8

In [14]:
b

array([1., 2., 3., 4.])

In [15]:
b.size  #total no. of digits

4

In [16]:
b.shape

(4,)

In [17]:
a.shape

(2, 2)

In [18]:
a=np.array([[1,2,3],
            [4,3,2]])
a.shape

(2, 3)

In [19]:
b=np.array([1,2,3,4],dtype=np.complex)
b

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [20]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [3, 2]])

In [22]:
a.ravel()

array([1, 2, 3, 4, 3, 2])

In [23]:
a

array([[1, 2, 3],
       [4, 3, 2]])

In [24]:
a.sum(axis=0)

array([5, 5, 5])

In [25]:
a.sum(axis=1)

array([6, 9])

In [26]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 1.73205081, 1.41421356]])

In [27]:
a


array([[1, 2, 3],
       [4, 3, 2]])

In [28]:
b

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [29]:
b=np.array([[2,3,1],
            [4,6,3]])

In [30]:
b

array([[2, 3, 1],
       [4, 6, 3]])

In [32]:
b.dot(a)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [42]:
c=np.array([[1,2],
          [2,3],
           [3,2]])
d=np.array([[3,4],
           [4,5],
           [6,2]])

In [43]:
c

array([[1, 2],
       [2, 3],
       [3, 2]])

In [45]:
d

array([[3, 4],
       [4, 5],
       [6, 2]])

# indexing and slicing

In [47]:
a=np.array([[1,2],
          [2,3],
           [3,2]])

In [48]:
for item in a.flat:
    print(item)

1
2
2
3
3
2


In [50]:
b=np.arange(6).reshape(3,2)

In [51]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [52]:
np.vstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 2],
       [0, 1],
       [2, 3],
       [4, 5]])

In [60]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
for i in np.nditer(a,order='f'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11
